aspectTypes:
  - name: data-product-biz-aspect-type
    displayName: Data Product Aspect
    description: Aspect for Data Product information
    type: record
    fields:
      - name: data_product_identifier
        type: string
        description: A unique identifier for the data product within your data governance system (e.g., Collibra).
        index: 1
        required: false
      - name: data_product_name
        type: string
        description: The name of the data product.
        index: 2
        required: false
      - name: data_product_description
        type: string
        description: A clear description of what the data product is, its contents, and its purpose.
        index: 3
        required: false
      - name: data_product_type
        type: enum
        values: ODP|FDP|CDP
        description: Type or category of the data product.
        index: 4
        required: false
      - name: platform_team
        type: string
        description: The business unit or team responsible for the data product.
        index: 5
        required: false
      - name: data_product_url
        type: string
        description: URL linking to the data product in the metadata catalog (e.g., Collibra or other metadata management systems).
        index: 6
        required: false
  - name: compliance-biz-aspect-type
    displayName: Compliance Aspect
    description: Aspect for Compliance information
    type: record
    fields:
      - name: retention_period
        type: enum
        values: Retention Periods|Data Privacy Domain|Collibra Data Governance Centre
        description: The duration of time for which the record should be held before archived/deleted.
        index: 1
        required: false
  - name: sensitivity-biz-aspect-type
    displayName: Sensitivity Aspect
    description: Aspect for Sensitivity information
    type: record
    fields:
      - name: security_classification
        type: enum
        values: Public|Limited|Confidential|Highly Confidential
        description: Classification of assets based on sensitivity.
        index: 1
        required: false
  - name: personal-biz-data-aspect-type
    displayName: Personal Data Aspect
    description: Aspect for Personal Data information
    type: record
    fields:
      - name: personal_data_indicator
        type: bool
        description: An indicator to flag an asset that could potentially be used to identify a specific individual.
        index: 1
        required: false
      - name: personal_data_category
        type: enum
        values: Personal Data Categories|Data Privacy Domain|Collibra Data Governance Centre
        description: Categories of personal data to categorize data used (mandatory only when Personal Data indicator is set to TRUE).
        index: 2
        required: false
  - name: legal-hold-biz-aspect-type
    displayName: Legal Hold Aspect
    description: Aspect for Legal Hold information
    type: record
    fields:
      - name: legal_hold_indicator
        type: bool
        description: An indicator to flag an asset as having a legal hold, also known as a litigation hold, to preserve all forms of relevant information when litigation is anticipated or ongoing.
        index: 1
        required: false
  - name: data-origin-biz-aspect-type
    displayName: Data Origin Aspect
    description: Aspect for Data Origin information
    type: record
    fields:
      - name: source_application_id
        type: string
        description: The unique identifier for the source application from which the data originates.
        index: 1
        required: false
      - name: source_application_name
        type: string
        description: The name of the source application.
        index: 2
        required: false
  - name: data-storage-tech-aspect-type
    displayName: Data Storage Aspect
    description: Aspect for Data Storage information
    type: record
    fields:
      - name: file_format
        type: string
        description: The format of the reciding data.
        index: 1
        required: false