aspectTypes:
  - name: data-quality-aspect
    displayName: Data Quality Aspect
    description: Aspect for data quality metrics
    type: record
    fields:
      - name: last_run
        type: string
        description: Last run date
        index: 1
        required: true
      - name: status
        type: string
        description: Status of the data quality check
        index: 2
        required: true
      - name: completeness
        type: string
        description: Completeness percentage
        index: 3
        required: true
      - name: accuracy
        type: string
        description: Accuracy percentage
        index: 4
        required: true
  - name: data-owner-aspect
    displayName: Data Owner Aspect
    description: Aspect for data owner information
    type: record
    fields:
      - name: owner
        type: string
        description: Data owner name
        index: 1
        required: true
      - name: email
        type: string
        description: Data owner email
        index: 2
        required: true