aspect_types:
  - aspect_type_id: data-owner-aspect
    gcp_project_id: burner-jubsharm
    location_id: us-central1
  - aspect_type_id: data-quality-aspect
    gcp_project_id: burner-jubsharm
    location_id: us-central1